apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-rest-recreate
  labels:
    app: spring-petclinic-rest
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-petclinic-rest
  template:
    metadata:
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
      - name: spring-petclinic-rest
        image: docker.io/springcommunity/spring-petclinic-rest:3.2.1
        ports:
        - containerPort: 9966
