apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T11:59:19Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "597"
  uid: 56ae23c2-7648-4218-b6e4-b18438c95a0b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.94.237
  clusterIPs:
  - 10.108.94.237
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31145
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}